FROM        --platform=$TARGETOS/$TARGETARCH node:14-bullseye-slim

LABEL       author="Heck" maintainer="admin@hecknode.com"

RUN         apt update \
            && apt -y install docker-compose \
            && useradd -m -d /home/container container

USER        container
ENV         USER=container HOME=/home/container
WORKDIR     /home/container

COPY        ./../entrypoint.sh /entrypoint.sh
CMD         [ "/bin/bash", "/entrypoint.sh" ]